name: Docker Image Release CI

on:
  push:
    tags: 
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t react-docker-app-demo:${{ env.TAG_NAME }} .

    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag react-docker-app-demo ${{ secrets.DOCKER_USERNAME }}/react-docker-app-demo:${{ env.TAG_NAME }}
        docker push ${{ secrets.DOCKER_USERNAME }}/react-docker-app-demo:${{ env.RELEASE_VERSION }}
